"use client";
import {useEffect,useState} from "react";
import {supabase} from "../lib/supabase";
const money=n=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(n||0);
export default function Home(){
 const [tab,setTab]=useState("Dashboard"),[sites,setSites]=useState([]),[updates,setUpdates]=useState([]),[expenses,setExpenses]=useState([]),[payments,setPayments]=useState([]);
 const [sf,setSf]=useState({name:"",client_name:"",location:"",contract_amount:""}),[uf,setUf]=useState({site_id:"",work_completed:"",labour_count:"",progress:""}),[ff,setFf]=useState({site_id:"",type:"expense",category:"Materials",amount:"",description:""});
 async function load(){let a=await Promise.all([supabase.from("sites").select("*").order("created_at",{ascending:false}),supabase.from("work_updates").select("*,sites(name)").order("created_at",{ascending:false}),supabase.from("expenses").select("*,sites(name)").order("created_at",{ascending:false}),supabase.from("payments").select("*,sites(name)").order("created_at",{ascending:false})]);setSites(a[0].data||[]);setUpdates(a[1].data||[]);setExpenses(a[2].data||[]);setPayments(a[3].data||[])}
 useEffect(()=>{load()},[]);
 async function addSite(e){e.preventDefault();let {error}=await supabase.from("sites").insert({...sf,contract_amount:+sf.contract_amount||0});if(error)return alert(error.message);setSf({name:"",client_name:"",location:"",contract_amount:""});load()}
 async function addUpdate(e){e.preventDefault();let p={site_id:uf.site_id,work_completed:uf.work_completed,labour_count:+uf.labour_count||0,progress:+uf.progress||0};let {error}=await supabase.from("work_updates").insert(p);if(error)return alert(error.message);await supabase.from("sites").update({progress:p.progress}).eq("id",p.site_id);setUf({site_id:"",work_completed:"",labour_count:"",progress:""});load()}
 async function addFinance(e){e.preventDefault();let p={site_id:ff.site_id,category:ff.category,amount:+ff.amount||0,description:ff.description};let {error}=await supabase.from(ff.type==="expense"?"expenses":"payments").insert(p);if(error)return alert(error.message);setFf({...ff,amount:"",description:""});load()}
 const contract=sites.reduce((a,s)=>a+(+s.contract_amount||0),0),ex=expenses.reduce((a,x)=>a+(+x.amount||0),0),pay=payments.reduce((a,x)=>a+(+x.amount||0),0),pl=pay-ex;
 const FormInput=({label,k})=><label>{label}<input value={sf[k]} onChange={e=>setSf({...sf,[k]:e.target.value})}/></label>;
 return <div className="app"><header><div><b>BUILDTRACK</b><small>Construction Site Manager</small></div><span>ADMIN</span></header><nav>{["Dashboard","Sites","Work Updates","Finance"].map(x=><button className={tab===x?"active":""} onClick={()=>setTab(x)} key={x}>{x}</button>)}</nav><main>
 {tab==="Dashboard"&&<><h1>Dashboard</h1><div className="stats"><Stat l="Active Sites" v={sites.filter(s=>s.status!=="Completed").length}/><Stat l="Contract Value" v={money(contract)}/><Stat l="Expenses" v={money(ex)}/><Stat l="Current P/L" v={money(pl)} c={pl>=0?"green":"red"}/></div><Panel title="Projects">{sites.map(s=><Site s={s} key={s.id}/>)}</Panel></>}
 {tab==="Sites"&&<><h1>Sites</h1><Panel title="Add New Site"><form onSubmit={addSite} className="form"><FormInput label="Site name" k="name"/><FormInput label="Client name" k="client_name"/><FormInput label="Location" k="location"/><FormInput label="Contract amount (₹)" k="contract_amount"/><button className="primary">Save Site</button></form></Panel><Panel title="All Sites">{sites.map(s=><Site s={s} key={s.id}/>)}</Panel></>}
 {tab==="Work Updates"&&<><h1>Work Updates</h1><Panel title="Add Work Update"><form onSubmit={addUpdate} className="form"><select required value={uf.site_id} onChange={e=>setUf({...uf,site_id:e.target.value})}><option value="">Select site</option>{sites.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><input placeholder="Labour count" type="number" value={uf.labour_count} onChange={e=>setUf({...uf,labour_count:e.target.value})}/><textarea required placeholder="Work completed" value={uf.work_completed} onChange={e=>setUf({...uf,work_completed:e.target.value})}/><input required placeholder="Progress %" type="number" min="0" max="100" value={uf.progress} onChange={e=>setUf({...uf,progress:e.target.value})}/><button className="primary">Save Update</button></form></Panel><Panel title="Recent Updates">{updates.map(u=><div className="item" key={u.id}><b>{u.sites?.name}</b><span>{u.progress}% · {u.labour_count} labour</span><p>{u.work_completed}</p></div>)}</Panel></>}
 {tab==="Finance"&&<><h1>Finance</h1><div className="stats"><Stat l="Payments" v={money(pay)} c="green"/><Stat l="Expenses" v={money(ex)} c="red"/><Stat l="Current P/L" v={money(pl)} c={pl>=0?"green":"red"}/></div><Panel title="Add Transaction"><form onSubmit={addFinance} className="form"><select required value={ff.site_id} onChange={e=>setFf({...ff,site_id:e.target.value})}><option value="">Select site</option>{sites.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><select value={ff.type} onChange={e=>setFf({...ff,type:e.target.value})}><option value="expense">Expense</option><option value="payment">Payment</option></select><input placeholder="Category" value={ff.category} onChange={e=>setFf({...ff,category:e.target.value})}/><input required placeholder="Amount" type="number" value={ff.amount} onChange={e=>setFf({...ff,amount:e.target.value})}/><input placeholder="Description" value={ff.description} onChange={e=>setFf({...ff,description:e.target.value})}/><button className="primary">Save Transaction</button></form></Panel></>}
 </main></div>}
function Stat({l,v,c=""}){return <div className="stat"><small>{l}</small><strong className={c}>{v}</strong></div>}
function Panel({title,children}){return <section className="panel"><h2>{title}</h2>{children}</section>}
function Site({s}){return <div className="site"><div className="row"><div><b>{s.name}</b><small>{s.client_name} · {s.location}</small></div><em>{s.status}</em></div><div className="bar"><i style={{width:(s.progress||0)+"%"}}/></div><div className="row"><small>{s.progress||0}% complete</small><b>{money(s.contract_amount)}</b></div></div>}
